project_name: gtree
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/gtree
    binary: gtree
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - CREDITS
release:
  prerelease: auto
brews:
  - tap:
      owner: ddddddO
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: 'https://github.com/ddddddO/gtree'
    description: 'Output tree🌳 or Make directories(files)📁 from Markdown.'
    license: "BSD-2-Clause"
scoop:
  bucket:
    owner: ddddddO
    name: scoop-bucket
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  url_template: "https://github.com/ddddddO/gtree/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  homepage: "https://github.com/ddddddO/gtree"
  description: "Output tree🌳 or Make directories(files)📁 from Markdown."
  license: "BSD-2-Clause"
