version: 2
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: golang:alpine
    steps:
      - checkout
      - run:
          name: echo test
          command: echo "test"

workflows:
  version: 2
  test-build:
    jobs:
      - build
