# https://qiita.com/kai_kou/items/eaafa3cb15e1496f50ec
version: '2'

services:
  pgdb:
    build:
      context: ../../../
      dockerfile: Dockerfiles/db/Dockerfile
    ports:
      - "15432:5432"

  sub1:
    build:
      context: ../../../
      dockerfile: Dockerfiles/app/sub/Dockerfile
    environment:
      - APP_NUMBER=1
    env_file:
      - pubsub.env
    depends_on:
      - "pgdb"

  sub2:
    build:
      context: ../../../
      dockerfile: Dockerfiles/app/sub/Dockerfile
    environment:
      - APP_NUMBER=2
    env_file:
      - pubsub.env
    depends_on:
      - "pgdb"

  pub:
    build:
      context: ../../../
      dockerfile: Dockerfiles/app/pub/Dockerfile
    env_file:
      - pubsub.env
    depends_on:
      - "pgdb"
      - "sub1"
      - "sub2"
