apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pubsubsys
spec:
  replicas: 2
  selector:
    matchLabels:
      sys: pubsub
  template:
    metadata:
      labels:
        sys: pubsub
    spec:
      containers:
        - name: db
          image: asia.gcr.io/work1111/db
        - name: sub
          image: asia.gcr.io/work1111/sub
          env:
            - name: DB_DSN
              value: host=localhost port=5432 user=postgres
        - name: pub
          image: asia.gcr.io/work1111/pub
          env:
            - name: DB_DSN
              value: host=localhost port=5432 user=postgres
