---
- name: create user
  hosts: all
  vars:
   #- password: "ユーザパスワード"
    - password: "upass"
  tasks:
    - name: create group
      group:
       #name: "グループ名"
        name: "newgrp"
        state: present
    - name: create user
      user:
       #name: "ユーザ名"
        name: "ddd"
        password: "{{ password | password_hash('sha512') }}"
       #groups: "グループ名",wheel
        groups: newgrp,wheel
        shell: /bin/bash
