apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps-db
spec:
  replicas: 1
  selector:
    matchLabels:
      sys: db
  template:
    metadata:
      labels:
        sys: db
    spec:
      containers:
        - name: db
          image: asia.gcr.io/work1111/db
          # ports でdbコンテナのportをexposeしなくともいけた
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-volume
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: database
---
apiVersion: v1
kind: Service
metadata:
  name: ps-db-svc
spec:
  selector:
    sys: db
  type: ClusterIP
  ports:
    - name: db-port
      port: 5432
