# https://qiita.com/kai_kou/items/eaafa3cb15e1496f50ec
version: '2'

services:
  pgdb:
    build:
      context: .
      dockerfile: Dockerfiles/db/Dockerfile
    ports:
      - "15432:5432"

  sub:
    build:
      context: .
      dockerfile: Dockerfiles/app/sub/Dockerfile
    depends_on:
      - "pgdb"

  pub:
    build:
      context: .
      dockerfile: Dockerfiles/app/pub/Dockerfile
    depends_on:
      - "pgdb"
      - "sub"
