apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pubsubsys
spec:
  replicas: 2
  selector:
    matchLabels:
      sys: pubsub
  template:
    metadata:
      labels:
        sys: pubsub
    spec:
      containers:
        - name: db
          image: db
          imagePullPolicy: Never
        - name: sub
          image: sub
          env:
            - name: DB_DSN
              value: host=localhost port=5432 user=postgres
          imagePullPolicy: Never
        - name: pub
          image: pub
          env:
            - name: DB_DSN
              value: host=localhost port=5432 user=postgres
          imagePullPolicy: Never
    
