name: ci
on: [push, pull_request]

jobs:
  test:
    name: test and coverage
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: checkout
        uses: actions/checkout@v3

      # - name: install gocognito
      #   run: go install github.com/nrnrk/gocognito/cmd/gocognito@latest
      # - name: compute cognitive
      #   run: gocognito . || echo 'Successful'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --issues-exit-code=0


      - name: test
        run: go test . -race -coverprofile=coverage.out -covermode=atomic -v
      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v3
